# Generated by Django 3.2.7 on 2021-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xebon',
            name='trangThaiXe',
            field=models.CharField(choices=[('R', 'Roi'), ('B', 'Ban')], max_length=5, null=True),
        ),
    ]
